[ldf_adapter]
# The Backend to use. Currently supported:
#  - local_unix
#  - bwidm
backend = bwidm

[assurance]
# One of 'cappuchino', 'espresso' or '*'
profile = *

# One of 'unique' or '*'
uid_uniqueness = unique
# One of 'no-reassign', 'reassign-1y' or '*'
eppn_uniqueness = no-reassign

# One of '*', 'low', 'medium' or 'high'
identity_assurance = low
# One of 'True' or 'False'
identity_qualifies_for_local_enterprise = True

# One of '1m', '1d' or '*'
attribute_freshness = 1d



[backend.local_unix]
# Backend specific configuration. No options are available for local_unix.

[backend.local_unix.login_info]
# Static information on how to login to this service.
description = Local SSH Test Service
login_help = Login via `ssh {login_name}@{login_host}` using one of your deployed keys.
login_host = <Hostname of the HDF-portal>


[backend.bwidm]
# The base URL of the BWIDM API
url = https://bwidm-test.scc.kit.edu/rest

# Primary group the user should be added to. E.g. Nico's group for testing HDF-LSDF:
primary_group_id = 1009662
# or Marcus' test group:
#primary_group_id = 1002637

# The ID of the organisation
org_id = hdf

[backend.bwidm.auth]
# HTTP basic auth to connect to BWIDM API
http_user = hdfrest
http_pass = hdfrest555634

[backend.bwidm.service]
# The name of the service the user should be added to on BWIDM:
name = sshtest

[backend.bwidm.login_info]
description = SSH Test Service
login_help = Login via `ssh {login_name}@{login_host*}` using one of your deployed keys.
login_host = hdf-login.lsdf.kit.edu
login_host_alternative = hdf-ssh.data.kit.edu
